// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/btccheckpoint/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryBtcCheckpointHeightAndHashRequest struct {
	// Number of epoch for which the earliest checkpointing btc height is requested
	EpochNum uint64 `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
}

func (m *QueryBtcCheckpointHeightAndHashRequest) Reset() {
	*m = QueryBtcCheckpointHeightAndHashRequest{}
}
func (m *QueryBtcCheckpointHeightAndHashRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBtcCheckpointHeightAndHashRequest) ProtoMessage()    {}
func (*QueryBtcCheckpointHeightAndHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{2}
}
func (m *QueryBtcCheckpointHeightAndHashRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBtcCheckpointHeightAndHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBtcCheckpointHeightAndHashRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBtcCheckpointHeightAndHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBtcCheckpointHeightAndHashRequest.Merge(m, src)
}
func (m *QueryBtcCheckpointHeightAndHashRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBtcCheckpointHeightAndHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBtcCheckpointHeightAndHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBtcCheckpointHeightAndHashRequest proto.InternalMessageInfo

func (m *QueryBtcCheckpointHeightAndHashRequest) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

// QueryBtcCheckpointHeightAndHashResponse is response type for the Query/BtcCheckpointHeightAndHash RPC method
type QueryBtcCheckpointHeightAndHashResponse struct {
	// Earliest btc block number containing given raw checkpoint
	EarliestBtcBlockNumber uint64 `protobuf:"varint,1,opt,name=earliest_btc_block_number,json=earliestBtcBlockNumber,proto3" json:"earliest_btc_block_number,omitempty"`
	EarliestBtcBlockHash   []byte `protobuf:"bytes,2,opt,name=earliest_btc_block_hash,json=earliestBtcBlockHash,proto3" json:"earliest_btc_block_hash,omitempty"`
}

func (m *QueryBtcCheckpointHeightAndHashResponse) Reset() {
	*m = QueryBtcCheckpointHeightAndHashResponse{}
}
func (m *QueryBtcCheckpointHeightAndHashResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBtcCheckpointHeightAndHashResponse) ProtoMessage()    {}
func (*QueryBtcCheckpointHeightAndHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{3}
}
func (m *QueryBtcCheckpointHeightAndHashResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBtcCheckpointHeightAndHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBtcCheckpointHeightAndHashResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBtcCheckpointHeightAndHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBtcCheckpointHeightAndHashResponse.Merge(m, src)
}
func (m *QueryBtcCheckpointHeightAndHashResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBtcCheckpointHeightAndHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBtcCheckpointHeightAndHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBtcCheckpointHeightAndHashResponse proto.InternalMessageInfo

func (m *QueryBtcCheckpointHeightAndHashResponse) GetEarliestBtcBlockNumber() uint64 {
	if m != nil {
		return m.EarliestBtcBlockNumber
	}
	return 0
}

func (m *QueryBtcCheckpointHeightAndHashResponse) GetEarliestBtcBlockHash() []byte {
	if m != nil {
		return m.EarliestBtcBlockHash
	}
	return nil
}

// QueryBtcCheckpointsHeightAndHashRequest is request type for the Query/BtcCheckpointsHeightAndHash RPC method
type QueryBtcCheckpointsHeightAndHashRequest struct {
	StartEpoch uint64 `protobuf:"varint,1,opt,name=start_epoch,json=startEpoch,proto3" json:"start_epoch,omitempty"`
	EndEpoch   uint64 `protobuf:"varint,2,opt,name=end_epoch,json=endEpoch,proto3" json:"end_epoch,omitempty"`
	// pagination defines whether to have the pagination in the response
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBtcCheckpointsHeightAndHashRequest) Reset() {
	*m = QueryBtcCheckpointsHeightAndHashRequest{}
}
func (m *QueryBtcCheckpointsHeightAndHashRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBtcCheckpointsHeightAndHashRequest) ProtoMessage()    {}
func (*QueryBtcCheckpointsHeightAndHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{4}
}
func (m *QueryBtcCheckpointsHeightAndHashRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBtcCheckpointsHeightAndHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBtcCheckpointsHeightAndHashRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBtcCheckpointsHeightAndHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBtcCheckpointsHeightAndHashRequest.Merge(m, src)
}
func (m *QueryBtcCheckpointsHeightAndHashRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBtcCheckpointsHeightAndHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBtcCheckpointsHeightAndHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBtcCheckpointsHeightAndHashRequest proto.InternalMessageInfo

func (m *QueryBtcCheckpointsHeightAndHashRequest) GetStartEpoch() uint64 {
	if m != nil {
		return m.StartEpoch
	}
	return 0
}

func (m *QueryBtcCheckpointsHeightAndHashRequest) GetEndEpoch() uint64 {
	if m != nil {
		return m.EndEpoch
	}
	return 0
}

func (m *QueryBtcCheckpointsHeightAndHashRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryBtcCheckpointsHeightAndHashResponse is response type for the Query/BtcCheckpointsHeightAndHash RPC method
type QueryBtcCheckpointsHeightAndHashResponse struct {
	EpochNumbers            []uint64 `protobuf:"varint,1,rep,packed,name=epoch_numbers,json=epochNumbers,proto3" json:"epoch_numbers,omitempty"`
	EarliestBtcBlockNumbers []uint64 `protobuf:"varint,2,rep,packed,name=earliest_btc_block_numbers,json=earliestBtcBlockNumbers,proto3" json:"earliest_btc_block_numbers,omitempty"`
	EarliestBtcBlockHashes  [][]byte `protobuf:"bytes,3,rep,name=earliest_btc_block_hashes,json=earliestBtcBlockHashes,proto3" json:"earliest_btc_block_hashes,omitempty"`
	// pagination defines the pagination in the response
	Pagination *query.PageResponse `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) Reset() {
	*m = QueryBtcCheckpointsHeightAndHashResponse{}
}
func (m *QueryBtcCheckpointsHeightAndHashResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBtcCheckpointsHeightAndHashResponse) ProtoMessage()    {}
func (*QueryBtcCheckpointsHeightAndHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{5}
}
func (m *QueryBtcCheckpointsHeightAndHashResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBtcCheckpointsHeightAndHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBtcCheckpointsHeightAndHashResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBtcCheckpointsHeightAndHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBtcCheckpointsHeightAndHashResponse.Merge(m, src)
}
func (m *QueryBtcCheckpointsHeightAndHashResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBtcCheckpointsHeightAndHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBtcCheckpointsHeightAndHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBtcCheckpointsHeightAndHashResponse proto.InternalMessageInfo

func (m *QueryBtcCheckpointsHeightAndHashResponse) GetEpochNumbers() []uint64 {
	if m != nil {
		return m.EpochNumbers
	}
	return nil
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) GetEarliestBtcBlockNumbers() []uint64 {
	if m != nil {
		return m.EarliestBtcBlockNumbers
	}
	return nil
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) GetEarliestBtcBlockHashes() [][]byte {
	if m != nil {
		return m.EarliestBtcBlockHashes
	}
	return nil
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryEpochSubmissionsRequest struct {
	// Number of epoch for which submissions are requested
	EpochNum   uint64             `protobuf:"varint,1,opt,name=epoch_num,json=epochNum,proto3" json:"epoch_num,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryEpochSubmissionsRequest) Reset()         { *m = QueryEpochSubmissionsRequest{} }
func (m *QueryEpochSubmissionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEpochSubmissionsRequest) ProtoMessage()    {}
func (*QueryEpochSubmissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{6}
}
func (m *QueryEpochSubmissionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochSubmissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochSubmissionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochSubmissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochSubmissionsRequest.Merge(m, src)
}
func (m *QueryEpochSubmissionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochSubmissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochSubmissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochSubmissionsRequest proto.InternalMessageInfo

func (m *QueryEpochSubmissionsRequest) GetEpochNum() uint64 {
	if m != nil {
		return m.EpochNum
	}
	return 0
}

func (m *QueryEpochSubmissionsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryEpochSubmissionsResponse struct {
	// All submissions saved during an epoch.
	Keys       []*SubmissionKey    `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryEpochSubmissionsResponse) Reset()         { *m = QueryEpochSubmissionsResponse{} }
func (m *QueryEpochSubmissionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEpochSubmissionsResponse) ProtoMessage()    {}
func (*QueryEpochSubmissionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_009c1165ec392ace, []int{7}
}
func (m *QueryEpochSubmissionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEpochSubmissionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEpochSubmissionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEpochSubmissionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEpochSubmissionsResponse.Merge(m, src)
}
func (m *QueryEpochSubmissionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEpochSubmissionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEpochSubmissionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEpochSubmissionsResponse proto.InternalMessageInfo

func (m *QueryEpochSubmissionsResponse) GetKeys() []*SubmissionKey {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *QueryEpochSubmissionsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "babylon.btccheckpoint.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "babylon.btccheckpoint.v1.QueryParamsResponse")
	proto.RegisterType((*QueryBtcCheckpointHeightAndHashRequest)(nil), "babylon.btccheckpoint.v1.QueryBtcCheckpointHeightAndHashRequest")
	proto.RegisterType((*QueryBtcCheckpointHeightAndHashResponse)(nil), "babylon.btccheckpoint.v1.QueryBtcCheckpointHeightAndHashResponse")
	proto.RegisterType((*QueryBtcCheckpointsHeightAndHashRequest)(nil), "babylon.btccheckpoint.v1.QueryBtcCheckpointsHeightAndHashRequest")
	proto.RegisterType((*QueryBtcCheckpointsHeightAndHashResponse)(nil), "babylon.btccheckpoint.v1.QueryBtcCheckpointsHeightAndHashResponse")
	proto.RegisterType((*QueryEpochSubmissionsRequest)(nil), "babylon.btccheckpoint.v1.QueryEpochSubmissionsRequest")
	proto.RegisterType((*QueryEpochSubmissionsResponse)(nil), "babylon.btccheckpoint.v1.QueryEpochSubmissionsResponse")
}

func init() { proto.RegisterFile("babylon/btccheckpoint/query.proto", fileDescriptor_009c1165ec392ace) }

var fileDescriptor_009c1165ec392ace = []byte{
	// 733 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x4f, 0x13, 0x41,
	0x14, 0xee, 0x6c, 0x0b, 0xd1, 0x01, 0x13, 0x33, 0x12, 0x29, 0x0b, 0x96, 0xb2, 0x46, 0xa8, 0x46,
	0x76, 0x53, 0x08, 0x1a, 0x42, 0x62, 0xa4, 0x06, 0x25, 0x31, 0x41, 0x5c, 0xe3, 0xc5, 0x4b, 0x33,
	0xbb, 0x4c, 0x76, 0x37, 0xb4, 0x3b, 0xcb, 0xce, 0x94, 0xd8, 0x18, 0x2f, 0xfa, 0x07, 0x48, 0xe2,
	0xd1, 0xb3, 0x67, 0xff, 0x03, 0xaf, 0x72, 0x24, 0xf1, 0xe2, 0xc9, 0x18, 0xf0, 0x7f, 0xf0, 0x6a,
	0x66, 0x76, 0x5a, 0x6c, 0xd9, 0xb5, 0xfc, 0xb8, 0x6d, 0x66, 0xbe, 0xf7, 0xbe, 0xef, 0x7d, 0xef,
	0xcd, 0x5b, 0x38, 0xe3, 0x60, 0xa7, 0xdd, 0xa0, 0xa1, 0xe5, 0x70, 0xd7, 0xf5, 0x89, 0xbb, 0x1d,
	0xd1, 0x20, 0xe4, 0xd6, 0x4e, 0x8b, 0xc4, 0x6d, 0x33, 0x8a, 0x29, 0xa7, 0xa8, 0xa8, 0x20, 0x66,
	0x0f, 0xc4, 0xdc, 0xad, 0xea, 0x63, 0x1e, 0xf5, 0xa8, 0x04, 0x59, 0xe2, 0x2b, 0xc1, 0xeb, 0x53,
	0x1e, 0xa5, 0x5e, 0x83, 0x58, 0x38, 0x0a, 0x2c, 0x1c, 0x86, 0x94, 0x63, 0x1e, 0xd0, 0x90, 0xa9,
	0xdb, 0x3b, 0x2e, 0x65, 0x4d, 0xca, 0x2c, 0x07, 0x33, 0x92, 0xd0, 0x58, 0xbb, 0x55, 0x87, 0x70,
	0x5c, 0xb5, 0x22, 0xec, 0x05, 0xa1, 0x04, 0x2b, 0xac, 0x91, 0x2e, 0x2e, 0xc2, 0x31, 0x6e, 0x76,
	0xf2, 0xdd, 0x4e, 0xc7, 0xf4, 0x6a, 0x95, 0x50, 0x63, 0x0c, 0xa2, 0xe7, 0x82, 0x70, 0x53, 0xc6,
	0xdb, 0x64, 0xa7, 0x45, 0x18, 0x37, 0x5e, 0xc2, 0x6b, 0x3d, 0xa7, 0x2c, 0xa2, 0x21, 0x23, 0xe8,
	0x01, 0x1c, 0x4e, 0x78, 0x8a, 0xa0, 0x0c, 0x2a, 0x23, 0x0b, 0x65, 0x33, 0xcb, 0x06, 0x33, 0x89,
	0xac, 0x15, 0xf6, 0x7f, 0x4e, 0xe7, 0x6c, 0x15, 0x65, 0xac, 0xc1, 0x59, 0x99, 0xb6, 0xc6, 0xdd,
	0x47, 0x5d, 0xf4, 0x3a, 0x09, 0x3c, 0x9f, 0xaf, 0x86, 0x5b, 0xeb, 0x98, 0xf9, 0x4a, 0x00, 0x9a,
	0x84, 0x97, 0x49, 0x44, 0x5d, 0xbf, 0x1e, 0xb6, 0x9a, 0x92, 0xac, 0x60, 0x5f, 0x92, 0x07, 0x1b,
	0xad, 0xa6, 0xf1, 0x09, 0xc0, 0xb9, 0x81, 0x79, 0x94, 0xe4, 0x65, 0x38, 0x41, 0x70, 0xdc, 0x08,
	0x08, 0xe3, 0x75, 0x87, 0xbb, 0x75, 0xa7, 0x41, 0xdd, 0x6d, 0x91, 0xd5, 0x21, 0xb1, 0x4a, 0x7c,
	0xbd, 0x03, 0xa8, 0x71, 0xb7, 0x26, 0xae, 0x37, 0xe4, 0x2d, 0x5a, 0x82, 0xe3, 0x29, 0xa1, 0x3e,
	0x66, 0x7e, 0x51, 0x2b, 0x83, 0xca, 0xa8, 0x3d, 0xd6, 0x1f, 0x28, 0x98, 0x8d, 0x2f, 0xa9, 0xea,
	0x58, 0x6a, 0x99, 0xd3, 0x70, 0x84, 0x71, 0x1c, 0xf3, 0xba, 0xac, 0x4d, 0xe9, 0x81, 0xf2, 0x68,
	0x4d, 0x9c, 0x48, 0x1f, 0xc2, 0x2d, 0x75, 0xad, 0x29, 0x1f, 0xc2, 0xad, 0xe4, 0xf2, 0x31, 0x84,
	0xc7, 0xe3, 0x51, 0xcc, 0xcb, 0x96, 0xcc, 0x9a, 0xc9, 0x2c, 0x99, 0x62, 0x96, 0xcc, 0x64, 0x64,
	0xd5, 0x2c, 0x99, 0x9b, 0xd8, 0x23, 0x8a, 0xd9, 0xfe, 0x27, 0xd2, 0xd8, 0xd3, 0x60, 0x65, 0xb0,
	0x62, 0x65, 0xe8, 0x4d, 0x78, 0xa5, 0xdb, 0x19, 0x87, 0xc4, 0x62, 0x14, 0xf2, 0x95, 0x82, 0x3d,
	0xda, 0xe9, 0x8e, 0x38, 0x43, 0x2b, 0x50, 0xcf, 0x74, 0x9d, 0x15, 0x35, 0x19, 0x31, 0x9e, 0x6e,
	0x3b, 0xcb, 0x68, 0x99, 0xf0, 0x9d, 0xb0, 0x62, 0xbe, 0x9c, 0xaf, 0x8c, 0x9e, 0x6c, 0xd9, 0xba,
	0xbc, 0x45, 0x4f, 0x7a, 0x1c, 0x29, 0x48, 0x47, 0xe6, 0x06, 0x3a, 0x92, 0x54, 0xd6, 0x63, 0xc9,
	0x7b, 0x00, 0xa7, 0xa4, 0x25, 0xd2, 0xe9, 0x17, 0x2d, 0xa7, 0x19, 0x30, 0x26, 0x5e, 0xec, 0x69,
	0x06, 0xb4, 0xaf, 0x31, 0xda, 0xb9, 0x1b, 0xf3, 0x19, 0xc0, 0x1b, 0x19, 0x2a, 0x54, 0x37, 0x56,
	0x60, 0x61, 0x9b, 0xb4, 0x93, 0x26, 0x88, 0x52, 0x33, 0xdf, 0xe3, 0x71, 0xf0, 0x53, 0xd2, 0xb6,
	0x65, 0x50, 0x9f, 0x5b, 0xda, 0xb9, 0xdd, 0x5a, 0xf8, 0x33, 0x04, 0x87, 0xa4, 0x4e, 0xf4, 0x01,
	0xc0, 0xe1, 0xe4, 0xe9, 0xa3, 0xbb, 0xd9, 0x62, 0x4e, 0x6e, 0x1c, 0x7d, 0xfe, 0x94, 0xe8, 0x84,
	0xdd, 0xa8, 0xbc, 0xfb, 0xfe, 0xfb, 0xa3, 0x66, 0xa0, 0xb2, 0x95, 0xbe, 0xea, 0x76, 0xab, 0x6a,
	0x23, 0xa2, 0x03, 0x00, 0xf5, 0xec, 0x3d, 0x81, 0x1e, 0x0e, 0xe0, 0x1d, 0xb8, 0xaa, 0xf4, 0xd5,
	0x0b, 0x64, 0x50, 0xd5, 0xcc, 0xcb, 0x6a, 0xe6, 0xd0, 0xad, 0xec, 0x6a, 0xde, 0x74, 0xa7, 0xed,
	0x2d, 0xfa, 0x06, 0xe0, 0xe4, 0x7f, 0x9e, 0x2a, 0x3a, 0x93, 0xa2, 0xd4, 0xc5, 0xa4, 0xd7, 0x2e,
	0x92, 0x42, 0x55, 0x35, 0x23, 0xab, 0x9a, 0x44, 0x13, 0x99, 0x55, 0xa1, 0xaf, 0x00, 0x5e, 0xed,
	0x9f, 0x6d, 0x74, 0x6f, 0x00, 0x77, 0xc6, 0x93, 0xd4, 0xef, 0x9f, 0x39, 0x4e, 0x09, 0x5d, 0x96,
	0x42, 0x17, 0x51, 0xf5, 0x54, 0xf6, 0x5b, 0xec, 0x38, 0x45, 0xed, 0xd9, 0xfe, 0x61, 0x09, 0x1c,
	0x1c, 0x96, 0xc0, 0xaf, 0xc3, 0x12, 0xd8, 0x3b, 0x2a, 0xe5, 0x0e, 0x8e, 0x4a, 0xb9, 0x1f, 0x47,
	0xa5, 0xdc, 0xab, 0x25, 0x2f, 0xe0, 0x7e, 0xcb, 0x31, 0x5d, 0xda, 0xec, 0xa4, 0x75, 0x7d, 0x1c,
	0x84, 0x5d, 0x8e, 0xd7, 0x7d, 0x2c, 0xbc, 0x1d, 0x11, 0xe6, 0x0c, 0xcb, 0xdf, 0xf2, 0xe2, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xe7, 0xea, 0xb4, 0x84, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// BtcCheckpointHeightAndHash returns earliest block height and hash for given rawcheckpoint
	BtcCheckpointHeightAndHash(ctx context.Context, in *QueryBtcCheckpointHeightAndHashRequest, opts ...grpc.CallOption) (*QueryBtcCheckpointHeightAndHashResponse, error)
	// BtcCheckpointsHeightAndHash returns earliest block height and hash for a range of epochs
	BtcCheckpointsHeightAndHash(ctx context.Context, in *QueryBtcCheckpointsHeightAndHashRequest, opts ...grpc.CallOption) (*QueryBtcCheckpointsHeightAndHashResponse, error)
	EpochSubmissions(ctx context.Context, in *QueryEpochSubmissionsRequest, opts ...grpc.CallOption) (*QueryEpochSubmissionsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/babylon.btccheckpoint.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BtcCheckpointHeightAndHash(ctx context.Context, in *QueryBtcCheckpointHeightAndHashRequest, opts ...grpc.CallOption) (*QueryBtcCheckpointHeightAndHashResponse, error) {
	out := new(QueryBtcCheckpointHeightAndHashResponse)
	err := c.cc.Invoke(ctx, "/babylon.btccheckpoint.v1.Query/BtcCheckpointHeightAndHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BtcCheckpointsHeightAndHash(ctx context.Context, in *QueryBtcCheckpointsHeightAndHashRequest, opts ...grpc.CallOption) (*QueryBtcCheckpointsHeightAndHashResponse, error) {
	out := new(QueryBtcCheckpointsHeightAndHashResponse)
	err := c.cc.Invoke(ctx, "/babylon.btccheckpoint.v1.Query/BtcCheckpointsHeightAndHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochSubmissions(ctx context.Context, in *QueryEpochSubmissionsRequest, opts ...grpc.CallOption) (*QueryEpochSubmissionsResponse, error) {
	out := new(QueryEpochSubmissionsResponse)
	err := c.cc.Invoke(ctx, "/babylon.btccheckpoint.v1.Query/EpochSubmissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// BtcCheckpointHeightAndHash returns earliest block height and hash for given rawcheckpoint
	BtcCheckpointHeightAndHash(context.Context, *QueryBtcCheckpointHeightAndHashRequest) (*QueryBtcCheckpointHeightAndHashResponse, error)
	// BtcCheckpointsHeightAndHash returns earliest block height and hash for a range of epochs
	BtcCheckpointsHeightAndHash(context.Context, *QueryBtcCheckpointsHeightAndHashRequest) (*QueryBtcCheckpointsHeightAndHashResponse, error)
	EpochSubmissions(context.Context, *QueryEpochSubmissionsRequest) (*QueryEpochSubmissionsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) BtcCheckpointHeightAndHash(ctx context.Context, req *QueryBtcCheckpointHeightAndHashRequest) (*QueryBtcCheckpointHeightAndHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BtcCheckpointHeightAndHash not implemented")
}
func (*UnimplementedQueryServer) BtcCheckpointsHeightAndHash(ctx context.Context, req *QueryBtcCheckpointsHeightAndHashRequest) (*QueryBtcCheckpointsHeightAndHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BtcCheckpointsHeightAndHash not implemented")
}
func (*UnimplementedQueryServer) EpochSubmissions(ctx context.Context, req *QueryEpochSubmissionsRequest) (*QueryEpochSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochSubmissions not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.btccheckpoint.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BtcCheckpointHeightAndHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBtcCheckpointHeightAndHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BtcCheckpointHeightAndHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.btccheckpoint.v1.Query/BtcCheckpointHeightAndHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BtcCheckpointHeightAndHash(ctx, req.(*QueryBtcCheckpointHeightAndHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BtcCheckpointsHeightAndHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBtcCheckpointsHeightAndHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BtcCheckpointsHeightAndHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.btccheckpoint.v1.Query/BtcCheckpointsHeightAndHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BtcCheckpointsHeightAndHash(ctx, req.(*QueryBtcCheckpointsHeightAndHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEpochSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babylon.btccheckpoint.v1.Query/EpochSubmissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochSubmissions(ctx, req.(*QueryEpochSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "babylon.btccheckpoint.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "BtcCheckpointHeightAndHash",
			Handler:    _Query_BtcCheckpointHeightAndHash_Handler,
		},
		{
			MethodName: "BtcCheckpointsHeightAndHash",
			Handler:    _Query_BtcCheckpointsHeightAndHash_Handler,
		},
		{
			MethodName: "EpochSubmissions",
			Handler:    _Query_EpochSubmissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "babylon/btccheckpoint/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBtcCheckpointHeightAndHashRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBtcCheckpointHeightAndHashRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBtcCheckpointHeightAndHashRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochNum != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryBtcCheckpointHeightAndHashResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBtcCheckpointHeightAndHashResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBtcCheckpointHeightAndHashResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EarliestBtcBlockHash) > 0 {
		i -= len(m.EarliestBtcBlockHash)
		copy(dAtA[i:], m.EarliestBtcBlockHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EarliestBtcBlockHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.EarliestBtcBlockNumber != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EarliestBtcBlockNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryBtcCheckpointsHeightAndHashRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBtcCheckpointsHeightAndHashRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBtcCheckpointsHeightAndHashRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.EndEpoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EndEpoch))
		i--
		dAtA[i] = 0x10
	}
	if m.StartEpoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.StartEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.EarliestBtcBlockHashes) > 0 {
		for iNdEx := len(m.EarliestBtcBlockHashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.EarliestBtcBlockHashes[iNdEx])
			copy(dAtA[i:], m.EarliestBtcBlockHashes[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.EarliestBtcBlockHashes[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.EarliestBtcBlockNumbers) > 0 {
		dAtA5 := make([]byte, len(m.EarliestBtcBlockNumbers)*10)
		var j4 int
		for _, num := range m.EarliestBtcBlockNumbers {
			for num >= 1<<7 {
				dAtA5[j4] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j4++
			}
			dAtA5[j4] = uint8(num)
			j4++
		}
		i -= j4
		copy(dAtA[i:], dAtA5[:j4])
		i = encodeVarintQuery(dAtA, i, uint64(j4))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EpochNumbers) > 0 {
		dAtA7 := make([]byte, len(m.EpochNumbers)*10)
		var j6 int
		for _, num := range m.EpochNumbers {
			for num >= 1<<7 {
				dAtA7[j6] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j6++
			}
			dAtA7[j6] = uint8(num)
			j6++
		}
		i -= j6
		copy(dAtA[i:], dAtA7[:j6])
		i = encodeVarintQuery(dAtA, i, uint64(j6))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEpochSubmissionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochSubmissionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochSubmissionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.EpochNum != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochNum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEpochSubmissionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEpochSubmissionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEpochSubmissionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Keys) > 0 {
		for iNdEx := len(m.Keys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Keys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBtcCheckpointHeightAndHashRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovQuery(uint64(m.EpochNum))
	}
	return n
}

func (m *QueryBtcCheckpointHeightAndHashResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EarliestBtcBlockNumber != 0 {
		n += 1 + sovQuery(uint64(m.EarliestBtcBlockNumber))
	}
	l = len(m.EarliestBtcBlockHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBtcCheckpointsHeightAndHashRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartEpoch != 0 {
		n += 1 + sovQuery(uint64(m.StartEpoch))
	}
	if m.EndEpoch != 0 {
		n += 1 + sovQuery(uint64(m.EndEpoch))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBtcCheckpointsHeightAndHashResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.EpochNumbers) > 0 {
		l = 0
		for _, e := range m.EpochNumbers {
			l += sovQuery(uint64(e))
		}
		n += 1 + sovQuery(uint64(l)) + l
	}
	if len(m.EarliestBtcBlockNumbers) > 0 {
		l = 0
		for _, e := range m.EarliestBtcBlockNumbers {
			l += sovQuery(uint64(e))
		}
		n += 1 + sovQuery(uint64(l)) + l
	}
	if len(m.EarliestBtcBlockHashes) > 0 {
		for _, b := range m.EarliestBtcBlockHashes {
			l = len(b)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEpochSubmissionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNum != 0 {
		n += 1 + sovQuery(uint64(m.EpochNum))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEpochSubmissionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Keys) > 0 {
		for _, e := range m.Keys {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBtcCheckpointHeightAndHashRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBtcCheckpointHeightAndHashRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBtcCheckpointHeightAndHashRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBtcCheckpointHeightAndHashResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBtcCheckpointHeightAndHashResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBtcCheckpointHeightAndHashResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarliestBtcBlockNumber", wireType)
			}
			m.EarliestBtcBlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EarliestBtcBlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarliestBtcBlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarliestBtcBlockHash = append(m.EarliestBtcBlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.EarliestBtcBlockHash == nil {
				m.EarliestBtcBlockHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBtcCheckpointsHeightAndHashRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBtcCheckpointsHeightAndHashRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBtcCheckpointsHeightAndHashRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartEpoch", wireType)
			}
			m.StartEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndEpoch", wireType)
			}
			m.EndEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBtcCheckpointsHeightAndHashResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBtcCheckpointsHeightAndHashResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBtcCheckpointsHeightAndHashResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.EpochNumbers = append(m.EpochNumbers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthQuery
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthQuery
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.EpochNumbers) == 0 {
					m.EpochNumbers = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.EpochNumbers = append(m.EpochNumbers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNumbers", wireType)
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.EarliestBtcBlockNumbers = append(m.EarliestBtcBlockNumbers, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthQuery
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthQuery
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.EarliestBtcBlockNumbers) == 0 {
					m.EarliestBtcBlockNumbers = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.EarliestBtcBlockNumbers = append(m.EarliestBtcBlockNumbers, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field EarliestBtcBlockNumbers", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarliestBtcBlockHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarliestBtcBlockHashes = append(m.EarliestBtcBlockHashes, make([]byte, postIndex-iNdEx))
			copy(m.EarliestBtcBlockHashes[len(m.EarliestBtcBlockHashes)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochSubmissionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochSubmissionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochSubmissionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNum", wireType)
			}
			m.EpochNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEpochSubmissionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEpochSubmissionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEpochSubmissionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Keys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Keys = append(m.Keys, &SubmissionKey{})
			if err := m.Keys[len(m.Keys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
