// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: babylon/epoching/v1/epoching.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Epoch struct {
	EpochNumber          uint64 `protobuf:"varint,1,opt,name=epoch_number,json=epochNumber,proto3" json:"epoch_number,omitempty"`
	CurrentEpochInterval uint64 `protobuf:"varint,2,opt,name=current_epoch_interval,json=currentEpochInterval,proto3" json:"current_epoch_interval,omitempty"`
	FirstBlockHeight     uint64 `protobuf:"varint,3,opt,name=first_block_height,json=firstBlockHeight,proto3" json:"first_block_height,omitempty"`
}

func (m *Epoch) Reset()         { *m = Epoch{} }
func (m *Epoch) String() string { return proto.CompactTextString(m) }
func (*Epoch) ProtoMessage()    {}
func (*Epoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f2f209d5311f84c, []int{0}
}
func (m *Epoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Epoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Epoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Epoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Epoch.Merge(m, src)
}
func (m *Epoch) XXX_Size() int {
	return m.Size()
}
func (m *Epoch) XXX_DiscardUnknown() {
	xxx_messageInfo_Epoch.DiscardUnknown(m)
}

var xxx_messageInfo_Epoch proto.InternalMessageInfo

func (m *Epoch) GetEpochNumber() uint64 {
	if m != nil {
		return m.EpochNumber
	}
	return 0
}

func (m *Epoch) GetCurrentEpochInterval() uint64 {
	if m != nil {
		return m.CurrentEpochInterval
	}
	return 0
}

func (m *Epoch) GetFirstBlockHeight() uint64 {
	if m != nil {
		return m.FirstBlockHeight
	}
	return 0
}

// QueuedMessage is a message that can change the validator set and is delayed to the epoch boundary
type QueuedMessage struct {
	// tx_id is the ID of the tx that contains the message
	TxId []byte `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// msg_id is the original message ID, i.e., hash of the marshaled message
	MsgId []byte `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// block_height is the height when this msg is submitted to Babylon
	BlockHeight uint64 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// msg is the actual message that is sent by a user and is queued by the epoching module
	//
	// Types that are valid to be assigned to Msg:
	//	*QueuedMessage_MsgCreateValidator
	//	*QueuedMessage_MsgDelegate
	//	*QueuedMessage_MsgUndelegate
	//	*QueuedMessage_MsgBeginRedelegate
	Msg isQueuedMessage_Msg `protobuf_oneof:"msg"`
}

func (m *QueuedMessage) Reset()         { *m = QueuedMessage{} }
func (m *QueuedMessage) String() string { return proto.CompactTextString(m) }
func (*QueuedMessage) ProtoMessage()    {}
func (*QueuedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f2f209d5311f84c, []int{1}
}
func (m *QueuedMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueuedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueuedMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueuedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedMessage.Merge(m, src)
}
func (m *QueuedMessage) XXX_Size() int {
	return m.Size()
}
func (m *QueuedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedMessage proto.InternalMessageInfo

type isQueuedMessage_Msg interface {
	isQueuedMessage_Msg()
	MarshalTo([]byte) (int, error)
	Size() int
}

type QueuedMessage_MsgCreateValidator struct {
	MsgCreateValidator *types.MsgCreateValidator `protobuf:"bytes,4,opt,name=msg_create_validator,json=msgCreateValidator,proto3,oneof" json:"msg_create_validator,omitempty"`
}
type QueuedMessage_MsgDelegate struct {
	MsgDelegate *types.MsgDelegate `protobuf:"bytes,5,opt,name=msg_delegate,json=msgDelegate,proto3,oneof" json:"msg_delegate,omitempty"`
}
type QueuedMessage_MsgUndelegate struct {
	MsgUndelegate *types.MsgUndelegate `protobuf:"bytes,6,opt,name=msg_undelegate,json=msgUndelegate,proto3,oneof" json:"msg_undelegate,omitempty"`
}
type QueuedMessage_MsgBeginRedelegate struct {
	MsgBeginRedelegate *types.MsgBeginRedelegate `protobuf:"bytes,7,opt,name=msg_begin_redelegate,json=msgBeginRedelegate,proto3,oneof" json:"msg_begin_redelegate,omitempty"`
}

func (*QueuedMessage_MsgCreateValidator) isQueuedMessage_Msg() {}
func (*QueuedMessage_MsgDelegate) isQueuedMessage_Msg()        {}
func (*QueuedMessage_MsgUndelegate) isQueuedMessage_Msg()      {}
func (*QueuedMessage_MsgBeginRedelegate) isQueuedMessage_Msg() {}

func (m *QueuedMessage) GetMsg() isQueuedMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *QueuedMessage) GetTxId() []byte {
	if m != nil {
		return m.TxId
	}
	return nil
}

func (m *QueuedMessage) GetMsgId() []byte {
	if m != nil {
		return m.MsgId
	}
	return nil
}

func (m *QueuedMessage) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *QueuedMessage) GetMsgCreateValidator() *types.MsgCreateValidator {
	if x, ok := m.GetMsg().(*QueuedMessage_MsgCreateValidator); ok {
		return x.MsgCreateValidator
	}
	return nil
}

func (m *QueuedMessage) GetMsgDelegate() *types.MsgDelegate {
	if x, ok := m.GetMsg().(*QueuedMessage_MsgDelegate); ok {
		return x.MsgDelegate
	}
	return nil
}

func (m *QueuedMessage) GetMsgUndelegate() *types.MsgUndelegate {
	if x, ok := m.GetMsg().(*QueuedMessage_MsgUndelegate); ok {
		return x.MsgUndelegate
	}
	return nil
}

func (m *QueuedMessage) GetMsgBeginRedelegate() *types.MsgBeginRedelegate {
	if x, ok := m.GetMsg().(*QueuedMessage_MsgBeginRedelegate); ok {
		return x.MsgBeginRedelegate
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueuedMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueuedMessage_MsgCreateValidator)(nil),
		(*QueuedMessage_MsgDelegate)(nil),
		(*QueuedMessage_MsgUndelegate)(nil),
		(*QueuedMessage_MsgBeginRedelegate)(nil),
	}
}

type ValidatorLifecycle struct {
	// val_addr is the address of the validator
	ValAddr string `protobuf:"bytes,1,opt,name=val_addr,json=valAddr,proto3" json:"val_addr,omitempty"`
	// bonding_request_height is the block height when this validator's creation request is received by Babylon
	// this happens when Babylon nodes commit the block that includes the `MsgWrappedCreateValidator` msg
	CreateRequestHeight uint64 `protobuf:"varint,2,opt,name=create_request_height,json=createRequestHeight,proto3" json:"create_request_height,omitempty"`
	// bonded_height is the block height when the validator's creation request is handled by Babylon and this validator becomes created (but still unbonded)
	// this happens at the end of an epoch
	CreatedHeight uint64 `protobuf:"varint,3,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	// bonding_request_height is the block height when this validator's bonding request is received by Babylon
	// this happens when Babylon nodes commit the block that includes the `MsgWrappedDelegate` msg
	BondingRequestHeight uint64 `protobuf:"varint,4,opt,name=bonding_request_height,json=bondingRequestHeight,proto3" json:"bonding_request_height,omitempty"`
	// bonded_height is the block height when the validator's bonding request is handled by Babylon and this validator becomes bonded
	// this happens at the end of an epoch
	BondedHeight uint64 `protobuf:"varint,5,opt,name=bonded_height,json=bondedHeight,proto3" json:"bonded_height,omitempty"`
	// unbonding_request_height is the block height when this validator's unbonding request is received by Babylon
	// this happens when Babylon nodes commit the block that includes the `MsgWrappedUndelegate` msg
	UnbondingRequestHeight uint64 `protobuf:"varint,6,opt,name=unbonding_request_height,json=unbondingRequestHeight,proto3" json:"unbonding_request_height,omitempty"`
	// unbonding_height is the block height when the validator's unbonding request is handled by Babylon and this validator becomes unbonding
	// this happens at the end of an epoch
	UnbondingHeight uint64 `protobuf:"varint,7,opt,name=unbonding_height,json=unbondingHeight,proto3" json:"unbonding_height,omitempty"`
	// unbonded_height is the block height when when this validator becomes uunbonded
	// this happens when the epoch's checkpoint is finalised
	UnbondedHeight uint64 `protobuf:"varint,8,opt,name=unbonded_height,json=unbondedHeight,proto3" json:"unbonded_height,omitempty"`
}

func (m *ValidatorLifecycle) Reset()         { *m = ValidatorLifecycle{} }
func (m *ValidatorLifecycle) String() string { return proto.CompactTextString(m) }
func (*ValidatorLifecycle) ProtoMessage()    {}
func (*ValidatorLifecycle) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f2f209d5311f84c, []int{2}
}
func (m *ValidatorLifecycle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorLifecycle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorLifecycle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorLifecycle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorLifecycle.Merge(m, src)
}
func (m *ValidatorLifecycle) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorLifecycle) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorLifecycle.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorLifecycle proto.InternalMessageInfo

func (m *ValidatorLifecycle) GetValAddr() string {
	if m != nil {
		return m.ValAddr
	}
	return ""
}

func (m *ValidatorLifecycle) GetCreateRequestHeight() uint64 {
	if m != nil {
		return m.CreateRequestHeight
	}
	return 0
}

func (m *ValidatorLifecycle) GetCreatedHeight() uint64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *ValidatorLifecycle) GetBondingRequestHeight() uint64 {
	if m != nil {
		return m.BondingRequestHeight
	}
	return 0
}

func (m *ValidatorLifecycle) GetBondedHeight() uint64 {
	if m != nil {
		return m.BondedHeight
	}
	return 0
}

func (m *ValidatorLifecycle) GetUnbondingRequestHeight() uint64 {
	if m != nil {
		return m.UnbondingRequestHeight
	}
	return 0
}

func (m *ValidatorLifecycle) GetUnbondingHeight() uint64 {
	if m != nil {
		return m.UnbondingHeight
	}
	return 0
}

func (m *ValidatorLifecycle) GetUnbondedHeight() uint64 {
	if m != nil {
		return m.UnbondedHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Epoch)(nil), "babylon.epoching.v1.Epoch")
	proto.RegisterType((*QueuedMessage)(nil), "babylon.epoching.v1.QueuedMessage")
	proto.RegisterType((*ValidatorLifecycle)(nil), "babylon.epoching.v1.ValidatorLifecycle")
}

func init() {
	proto.RegisterFile("babylon/epoching/v1/epoching.proto", fileDescriptor_2f2f209d5311f84c)
}

var fileDescriptor_2f2f209d5311f84c = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xd3, 0x30,
	0x1c, 0xc7, 0x93, 0xad, 0xe9, 0x86, 0xdb, 0x8e, 0xc9, 0xfb, 0xa3, 0xb0, 0x43, 0x18, 0x9d, 0x26,
	0x06, 0x42, 0x09, 0x1b, 0x3b, 0x70, 0xa5, 0x80, 0xd4, 0x21, 0x36, 0x89, 0x48, 0x70, 0xe0, 0x40,
	0xe4, 0xc4, 0x9e, 0x1b, 0x2d, 0x89, 0x47, 0xec, 0x44, 0xed, 0x4b, 0x20, 0xde, 0x88, 0x2b, 0xc7,
	0x1d, 0x39, 0xa2, 0xf6, 0x11, 0x78, 0x01, 0x14, 0xdb, 0x4d, 0xd6, 0x01, 0xe3, 0x96, 0x7c, 0xff,
	0x7c, 0x12, 0xfb, 0x67, 0x19, 0xf4, 0x43, 0x14, 0x4e, 0x12, 0x96, 0x79, 0xe4, 0x92, 0x45, 0xa3,
	0x38, 0xa3, 0x5e, 0x79, 0x58, 0x3f, 0xbb, 0x97, 0x39, 0x13, 0x0c, 0x6e, 0xe8, 0x8c, 0x5b, 0xeb,
	0xe5, 0xe1, 0xce, 0x26, 0x65, 0x94, 0x49, 0xdf, 0xab, 0x9e, 0x54, 0x74, 0xe7, 0x7e, 0xc4, 0x78,
	0xca, 0xb8, 0xc7, 0x05, 0xba, 0x50, 0xb0, 0x90, 0x08, 0x74, 0xe8, 0x89, 0xb1, 0x0a, 0xf4, 0xbf,
	0x98, 0xc0, 0x7a, 0x5d, 0x61, 0xe0, 0x03, 0xd0, 0x95, 0xbc, 0x20, 0x2b, 0xd2, 0x90, 0xe4, 0xb6,
	0xb9, 0x6b, 0x1e, 0xb4, 0xfc, 0x8e, 0xd4, 0xce, 0xa4, 0x04, 0x8f, 0xc1, 0x76, 0x54, 0xe4, 0x39,
	0xc9, 0x44, 0xa0, 0xa2, 0x71, 0x26, 0x48, 0x5e, 0xa2, 0xc4, 0x5e, 0x92, 0xe1, 0x4d, 0xed, 0x4a,
	0xe0, 0x89, 0xf6, 0xe0, 0x13, 0x00, 0xcf, 0xe3, 0x9c, 0x8b, 0x20, 0x4c, 0x58, 0x74, 0x11, 0x8c,
	0x48, 0x4c, 0x47, 0xc2, 0x5e, 0x96, 0x8d, 0x75, 0xe9, 0x0c, 0x2a, 0x63, 0x28, 0xf5, 0xfe, 0xb7,
	0x65, 0xd0, 0x7b, 0x57, 0x90, 0x82, 0xe0, 0x53, 0xc2, 0x39, 0xa2, 0x04, 0x6e, 0x00, 0x4b, 0x8c,
	0x83, 0x18, 0xcb, 0x3f, 0xea, 0xfa, 0x2d, 0x31, 0x3e, 0xc1, 0x70, 0x0b, 0xb4, 0x53, 0x4e, 0x2b,
	0x75, 0x49, 0xaa, 0x56, 0xca, 0xe9, 0x09, 0xae, 0x16, 0xf1, 0x97, 0xaf, 0x74, 0xc2, 0xe6, 0x03,
	0xf0, 0x13, 0xd8, 0xac, 0x9a, 0x51, 0x4e, 0x90, 0x20, 0x41, 0x89, 0x92, 0x18, 0x23, 0xc1, 0x72,
	0xbb, 0xb5, 0x6b, 0x1e, 0x74, 0x8e, 0x1e, 0xbb, 0x6a, 0xc7, 0x5c, 0xbd, 0x63, 0xae, 0xde, 0x31,
	0xf7, 0x94, 0xd3, 0x97, 0xb2, 0xf2, 0x61, 0xde, 0x18, 0x1a, 0x3e, 0x4c, 0xff, 0x50, 0xe1, 0x10,
	0x74, 0x2b, 0x3e, 0x26, 0x09, 0xa1, 0x48, 0x10, 0xdb, 0x92, 0xdc, 0xbd, 0x5b, 0xb8, 0xaf, 0x74,
	0x74, 0x68, 0xf8, 0x9d, 0xb4, 0x79, 0x85, 0x67, 0x60, 0xad, 0x22, 0x15, 0x59, 0xcd, 0x6a, 0x4b,
	0xd6, 0xfe, 0x2d, 0xac, 0xf7, 0x75, 0x78, 0x68, 0xf8, 0xbd, 0xf4, 0xba, 0x30, 0x5f, 0x79, 0x48,
	0x68, 0x9c, 0x05, 0x39, 0xa9, 0xa9, 0x2b, 0xff, 0x5d, 0xf9, 0xa0, 0xaa, 0xf8, 0xe4, 0x1a, 0xba,
	0x5a, 0xf9, 0x0d, 0x75, 0x60, 0x81, 0xe5, 0x94, 0xd3, 0xfe, 0xaf, 0x25, 0x00, 0xeb, 0xed, 0x78,
	0x1b, 0x9f, 0x93, 0x68, 0x12, 0x25, 0x04, 0xde, 0x03, 0xab, 0x25, 0x4a, 0x02, 0x84, 0xb1, 0x3a,
	0x5b, 0x77, 0xfc, 0x95, 0x12, 0x25, 0x2f, 0x30, 0xce, 0xe1, 0x11, 0xd8, 0xd2, 0xe3, 0xc8, 0xc9,
	0xe7, 0x82, 0x70, 0x31, 0x1f, 0x9f, 0x3a, 0x56, 0x1b, 0xca, 0xf4, 0x95, 0xa7, 0xc7, 0xb8, 0x0f,
	0xd6, 0x94, 0x8c, 0x17, 0x67, 0xdd, 0xd3, 0xaa, 0x8e, 0x1d, 0x83, 0xed, 0x90, 0x65, 0x38, 0xce,
	0xe8, 0x4d, 0x76, 0x4b, 0x1d, 0x59, 0xed, 0x2e, 0xc2, 0xf7, 0x40, 0xaf, 0xd2, 0x1b, 0xb6, 0x25,
	0xc3, 0x5d, 0x25, 0xea, 0xd0, 0x73, 0x60, 0x17, 0xd9, 0x3f, 0xe0, 0x6d, 0x99, 0xdf, 0xae, 0xfd,
	0x45, 0xfc, 0x23, 0xb0, 0xde, 0x34, 0x75, 0x63, 0x45, 0x36, 0xee, 0xd6, 0xba, 0x8e, 0x3e, 0x04,
	0x5a, 0x6a, 0xfe, 0x65, 0x55, 0x26, 0xd7, 0xe6, 0xb2, 0x0a, 0x0e, 0xde, 0x7c, 0x9f, 0x3a, 0xe6,
	0xd5, 0xd4, 0x31, 0x7f, 0x4e, 0x1d, 0xf3, 0xeb, 0xcc, 0x31, 0xae, 0x66, 0x8e, 0xf1, 0x63, 0xe6,
	0x18, 0x1f, 0x9f, 0xd2, 0x58, 0x8c, 0x8a, 0xd0, 0x8d, 0x58, 0xea, 0xe9, 0x9b, 0x23, 0x1a, 0xa1,
	0x38, 0x9b, 0xbf, 0x78, 0xe3, 0xe6, 0xb2, 0x11, 0x93, 0x4b, 0xc2, 0xc3, 0xb6, 0xbc, 0x1b, 0x9e,
	0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x04, 0xd8, 0x7a, 0x24, 0x8d, 0x04, 0x00, 0x00,
}

func (m *Epoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Epoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Epoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FirstBlockHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.FirstBlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.CurrentEpochInterval != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.CurrentEpochInterval))
		i--
		dAtA[i] = 0x10
	}
	if m.EpochNumber != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.EpochNumber))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueuedMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueuedMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Msg != nil {
		{
			size := m.Msg.Size()
			i -= size
			if _, err := m.Msg.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.BlockHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MsgId) > 0 {
		i -= len(m.MsgId)
		copy(dAtA[i:], m.MsgId)
		i = encodeVarintEpoching(dAtA, i, uint64(len(m.MsgId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintEpoching(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueuedMessage_MsgCreateValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedMessage_MsgCreateValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MsgCreateValidator != nil {
		{
			size, err := m.MsgCreateValidator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEpoching(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *QueuedMessage_MsgDelegate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedMessage_MsgDelegate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MsgDelegate != nil {
		{
			size, err := m.MsgDelegate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEpoching(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *QueuedMessage_MsgUndelegate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedMessage_MsgUndelegate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MsgUndelegate != nil {
		{
			size, err := m.MsgUndelegate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEpoching(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	return len(dAtA) - i, nil
}
func (m *QueuedMessage_MsgBeginRedelegate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedMessage_MsgBeginRedelegate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.MsgBeginRedelegate != nil {
		{
			size, err := m.MsgBeginRedelegate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEpoching(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *ValidatorLifecycle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorLifecycle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorLifecycle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UnbondedHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.UnbondedHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.UnbondingHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.UnbondingHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.UnbondingRequestHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.UnbondingRequestHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.BondedHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.BondedHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.BondingRequestHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.BondingRequestHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.CreateRequestHeight != 0 {
		i = encodeVarintEpoching(dAtA, i, uint64(m.CreateRequestHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValAddr) > 0 {
		i -= len(m.ValAddr)
		copy(dAtA[i:], m.ValAddr)
		i = encodeVarintEpoching(dAtA, i, uint64(len(m.ValAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEpoching(dAtA []byte, offset int, v uint64) int {
	offset -= sovEpoching(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Epoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochNumber != 0 {
		n += 1 + sovEpoching(uint64(m.EpochNumber))
	}
	if m.CurrentEpochInterval != 0 {
		n += 1 + sovEpoching(uint64(m.CurrentEpochInterval))
	}
	if m.FirstBlockHeight != 0 {
		n += 1 + sovEpoching(uint64(m.FirstBlockHeight))
	}
	return n
}

func (m *QueuedMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovEpoching(uint64(l))
	}
	l = len(m.MsgId)
	if l > 0 {
		n += 1 + l + sovEpoching(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovEpoching(uint64(m.BlockHeight))
	}
	if m.Msg != nil {
		n += m.Msg.Size()
	}
	return n
}

func (m *QueuedMessage_MsgCreateValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgCreateValidator != nil {
		l = m.MsgCreateValidator.Size()
		n += 1 + l + sovEpoching(uint64(l))
	}
	return n
}
func (m *QueuedMessage_MsgDelegate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgDelegate != nil {
		l = m.MsgDelegate.Size()
		n += 1 + l + sovEpoching(uint64(l))
	}
	return n
}
func (m *QueuedMessage_MsgUndelegate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgUndelegate != nil {
		l = m.MsgUndelegate.Size()
		n += 1 + l + sovEpoching(uint64(l))
	}
	return n
}
func (m *QueuedMessage_MsgBeginRedelegate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgBeginRedelegate != nil {
		l = m.MsgBeginRedelegate.Size()
		n += 1 + l + sovEpoching(uint64(l))
	}
	return n
}
func (m *ValidatorLifecycle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddr)
	if l > 0 {
		n += 1 + l + sovEpoching(uint64(l))
	}
	if m.CreateRequestHeight != 0 {
		n += 1 + sovEpoching(uint64(m.CreateRequestHeight))
	}
	if m.CreatedHeight != 0 {
		n += 1 + sovEpoching(uint64(m.CreatedHeight))
	}
	if m.BondingRequestHeight != 0 {
		n += 1 + sovEpoching(uint64(m.BondingRequestHeight))
	}
	if m.BondedHeight != 0 {
		n += 1 + sovEpoching(uint64(m.BondedHeight))
	}
	if m.UnbondingRequestHeight != 0 {
		n += 1 + sovEpoching(uint64(m.UnbondingRequestHeight))
	}
	if m.UnbondingHeight != 0 {
		n += 1 + sovEpoching(uint64(m.UnbondingHeight))
	}
	if m.UnbondedHeight != 0 {
		n += 1 + sovEpoching(uint64(m.UnbondedHeight))
	}
	return n
}

func sovEpoching(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEpoching(x uint64) (n int) {
	return sovEpoching(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Epoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Epoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Epoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochNumber", wireType)
			}
			m.EpochNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpochInterval", wireType)
			}
			m.CurrentEpochInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpochInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstBlockHeight", wireType)
			}
			m.FirstBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEpoching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueuedMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueuedMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueuedMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEpoching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = append(m.TxId[:0], dAtA[iNdEx:postIndex]...)
			if m.TxId == nil {
				m.TxId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEpoching
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgId = append(m.MsgId[:0], dAtA[iNdEx:postIndex]...)
			if m.MsgId == nil {
				m.MsgId = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgCreateValidator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoching
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.MsgCreateValidator{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Msg = &QueuedMessage_MsgCreateValidator{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgDelegate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoching
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.MsgDelegate{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Msg = &QueuedMessage_MsgDelegate{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgUndelegate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoching
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.MsgUndelegate{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Msg = &QueuedMessage_MsgUndelegate{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgBeginRedelegate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEpoching
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEpoching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &types.MsgBeginRedelegate{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Msg = &QueuedMessage_MsgBeginRedelegate{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpoching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorLifecycle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpoching
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorLifecycle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorLifecycle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpoching
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpoching
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateRequestHeight", wireType)
			}
			m.CreateRequestHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreateRequestHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingRequestHeight", wireType)
			}
			m.BondingRequestHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondingRequestHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondedHeight", wireType)
			}
			m.BondedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingRequestHeight", wireType)
			}
			m.UnbondingRequestHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingRequestHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingHeight", wireType)
			}
			m.UnbondingHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondedHeight", wireType)
			}
			m.UnbondedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEpoching(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpoching
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEpoching(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEpoching
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpoching
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEpoching
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEpoching
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEpoching
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEpoching        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEpoching          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEpoching = fmt.Errorf("proto: unexpected end of group")
)
