@startuml Validator Registration
actor       User
participant CLI
control     Tendermint
queue       Mempool
participant "Checkpointing Module" as checkpointing
participant "Epoching Module" as epoching
database    "BLS Keys"        as blskeys
queue       "Delayed Txs"     as delayedtxs
participant "Staking Module"  as staking
queue       Events

== Create User Transaction ==

User -> CLI ++ : bbnd tx staking create-validator ... \n --generate-only
return unsigned_staking_tx.json
User -> CLI ++ : bbnd tx checkpointing create-validator \n ~--wrap unsigned_staking_tx.json \n ~--bls-key ... --generate-only
return unsigned_checkpointing_tx.json
User -> CLI ++ : bbnd tx sign unsigned_checkpointing_tx.json
return signed_checkpointing_tx.json
User -> CLI : bbnd tx broadcast signed_checkpointing_tx.json

CLI -> Tendermint ++ : signed_checkpointing_tx
Tendermint -> checkpointing ++ : CheckTx
checkpointing -> checkpointing : Validate BLS Proof-of-Possession
checkpointing -> blskeys ++ : Validate User-BLS association
return ok or error if different from existing key
return success or failure
Tendermint -> Mempool : Add tx
deactivate Tendermint
note left
  The user can wait for the results as well,
  but we don't check or lock funds.
end note

... Wait for the transaction to be included in a block ...

== Deliver Transaction in a Block ==

Tendermint -> checkpointing ++ : DeliverTx
checkpointing -> checkpointing : Validate BLS Proof-of-Possession
checkpointing -> blskeys ++ : Add User-BLS association if new
return ok or error if different from existing key
checkpointing -> epoching ++ : Append wrapped staking tx
epoching -> delayedtxs -- : Append to delayed staking txs

return result or invalid

== EndBlock at the end of an Epoch ==

Tendermint -> staking !! : EndBlock is prevented from running
Tendermint -> epoching ++ : EndBlock
epoching -> delayedtxs ++ : Dequeue delayed txs
return wrapped staking txs
loop foreach wrapped tx
  epoching -> staking ++ : runTx wrapped tx
  return result or invalid
  epoching -> Events : Emit feedback about delayed tx outcome
end
epoching -> staking ++ : ApplyAndReturnValidatorSetUpdates
return ValidatorSetUpdates
return ValidatorSetUpdates

Events --> User : Observe delayed tx outcome

@enduml
